In [38]:
import pandas as pd

In [39]:
dfbki = pd.read_excel("Excel-Files/BKIJahr.xlsx")
dfbki

,Zürcher Index der Wohnbaukosten,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,jährliche Steigerung in %,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bezeichnung,Basis,Jahr,Stand¹,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CH,1939,1939,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CH,1939,1940,112.4,NaN,0.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CH,1939,1941,129.6,NaN,0.153025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CH,1939,1942,146,NaN,0.126543,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CH,1939,1943,152.4,NaN,0.043836,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,CH,1939,1944,157.9,NaN,0.036089,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,CH,1939,1945,163.7,NaN,0.036732,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CH,1939,1946,176.7,NaN,0.079414,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,CH,1939,1947,194.2,NaN,0.099038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,CH,1939,1948,197.1,NaN,0.014933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,CH,1939,1949,189.4,NaN,-0.039066,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CH,1939,1950,179.5,NaN,-0.05227,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CH,1939,1951,197.3,NaN,0.099164,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,CH,1939,1952,203.8,NaN,0.032945,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,CH,1939,1953,197.5,NaN,-0.030913,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,CH,1939,1954,193.3,NaN,-0.021266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,CH,1939,1955,201.1,NaN,0.040352,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,CH,1939,1956,206.4,NaN,0.026355,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,CH,1939,1957,212.9,NaN,0.031492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,CH,1939,1958,212.5,NaN,-0.001879,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,CH,1939,1959,215.1,NaN,0.012235,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,CH,1939,1960,219.7,NaN,0.021385,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,CH,1939,1961,237.1,NaN,0.079199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,CH,1939,1962,257.9,NaN,0.087727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,CH,1939,1963,277.5,NaN,0.075998,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,CH,1939,1964,297.6,NaN,0.072432,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,CH,1939,1965,310.6,NaN,0.043683,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,CH,1939,1966,319.7,NaN,0.029298,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,CH,1939,1967,322.6,NaN,0.009071,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,CH,1939,1968,325.4,NaN,0.008679,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,CH,1939,1969,331.4,NaN,0.018439,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,CH,1939,1970,374.7,NaN,0.130658,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,CH,1939,1971,421.2,NaN,0.124099,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,CH,1939,1972,466,NaN,0.106363,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,CH,1939,1973,512.7,NaN,0.100215,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,CH,1939,1974,557.5,NaN,0.087381,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,CH,1939,1975,535.5,NaN,-0.039462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,CH,1939,1976,500.4,NaN,-0.065546,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,CH,1939,1977,515.1,NaN,0.029376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,CH,1939,1978,533.1,NaN,0.034945,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,CH,1939,1979,549.2,NaN,0.030201,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,CH,1939,1980,600,NaN,0.092498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,CH,1939,1981,654.1,NaN,0.090167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,CH,1939,1982,698.4,NaN,0.067727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,CH,1939,1983,670.2,NaN,-0.040378,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,CH,1939,1984,670.3,NaN,0.000149,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,CH,1939,1985,684.8,NaN,0.021632,NaN,NaN,NaN,NaN,Baukostenindex,NaN,NaN
49,CH,1939,1986,705.2,NaN,0.02979,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,CH,1939,1987,718.9,NaN,0.019427,NaN,NaN,NaN,NaN,Umrechnung,NaN,NaN
51,CH,1939,1988,750.3,NaN,0.043678,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,CH,1939,1989,790.1,NaN,0.053045,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,CH,1939,1990,858.5,NaN,0.086571,NaN,NaN,NaN,NaN,Index bisher,NaN,Summe bisher
54,CH,1939,1991,911.2,NaN,0.061386,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,CH,1939,1992,905.2,NaN,-0.006585,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,CH,1939,1993,863.8,NaN,-0.045736,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,CH,1939,1994,853.1,NaN,-0.012387,NaN,NaN,NaN,NaN,Index neu,NaN,Summe neu
58,CH,1939,1995,874.2,NaN,0.024733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,CH,1939,1996,861.4,NaN,-0.014642,NaN,NaN,NaN,NaN,987.4,NaN,NaN
60,CH,1939,1997,847.4,NaN,-0.016253,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,CH,1939,1998,843.8,NaN,-0.004248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,CH,1939,1999,854.4,NaN,0.012562,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,CH,1939,2000,887.1,NaN,0.038272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,CH,1939,2001,929.3,NaN,0.047571,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,CH,1939,2002,928.4,NaN,-0.000968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,CH,1939,2003,899.2,NaN,-0.031452,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,CH,1939,2004,907.6,NaN,0.009342,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,CH,1939,2005,929.5,NaN,0.02413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,CH,1939,2006,944.5,NaN,0.016138,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,CH,1939,2007,987.4,NaN,0.045421,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,CH,1939,2008,1026.8,NaN,0.039903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,CH,1939,2009,1030.7,NaN,0.003798,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,CH,1939,2010,1042.6,NaN,0.011546,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,CH,1939,2011,1059.8,NaN,0.016497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,CH,1939,2012,1067.4,NaN,0.007171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,CH,1939,2013,1060.9,NaN,-0.00609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,CH,1939,2014,1066.1,NaN,0.004901,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,CH,1939,2015,1053.2,NaN,-0.0121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,CH,1939,2016,1034.4,NaN,-0.01785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,CH,1939,2017,1034.5,NaN,0.000097,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,CH,1939,2018,1036.8,NaN,0.002223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,CH,1939,2019,1046.3,NaN,0.009163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,CH,1939,2020,1045.6,NaN,-0.000669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,CH,1939,2021,1057.7,NaN,0.011572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,CH,1939,2022,1128.6,NaN,0.067032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,2022-10-28 00:00:00,Karl Laternser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
dfbki.drop(dfbki.index[2:63], inplace=True)
dfbki

,Zürcher Index der Wohnbaukosten,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,jährliche Steigerung in %,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bezeichnung,Basis,Jahr,Stand¹,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,CH,1939,2000,887.1,NaN,0.038272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,CH,1939,2001,929.3,NaN,0.047571,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,CH,1939,2002,928.4,NaN,-0.000968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,CH,1939,2003,899.2,NaN,-0.031452,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,CH,1939,2004,907.6,NaN,0.009342,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,CH,1939,2005,929.5,NaN,0.02413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,CH,1939,2006,944.5,NaN,0.016138,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,CH,1939,2007,987.4,NaN,0.045421,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,CH,1939,2008,1026.8,NaN,0.039903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,CH,1939,2009,1030.7,NaN,0.003798,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,CH,1939,2010,1042.6,NaN,0.011546,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,CH,1939,2011,1059.8,NaN,0.016497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,CH,1939,2012,1067.4,NaN,0.007171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,CH,1939,2013,1060.9,NaN,-0.00609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,CH,1939,2014,1066.1,NaN,0.004901,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,CH,1939,2015,1053.2,NaN,-0.0121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,CH,1939,2016,1034.4,NaN,-0.01785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,CH,1939,2017,1034.5,NaN,0.000097,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,CH,1939,2018,1036.8,NaN,0.002223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,CH,1939,2019,1046.3,NaN,0.009163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,CH,1939,2020,1045.6,NaN,-0.000669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,CH,1939,2021,1057.7,NaN,0.011572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,CH,1939,2022,1128.6,NaN,0.067032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,2022-10-28 00:00:00,Karl Laternser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
dfbki = dfbki.reset_index()
dfbki

,index,Zürcher Index der Wohnbaukosten,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,0,NaN,NaN,NaN,NaN,NaN,jährliche Steigerung in %,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Bezeichnung,Basis,Jahr,Stand¹,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,63,CH,1939,2000,887.1,NaN,0.038272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,64,CH,1939,2001,929.3,NaN,0.047571,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,65,CH,1939,2002,928.4,NaN,-0.000968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,66,CH,1939,2003,899.2,NaN,-0.031452,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,67,CH,1939,2004,907.6,NaN,0.009342,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,68,CH,1939,2005,929.5,NaN,0.02413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,69,CH,1939,2006,944.5,NaN,0.016138,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,70,CH,1939,2007,987.4,NaN,0.045421,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,71,CH,1939,2008,1026.8,NaN,0.039903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,72,CH,1939,2009,1030.7,NaN,0.003798,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,73,CH,1939,2010,1042.6,NaN,0.011546,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,74,CH,1939,2011,1059.8,NaN,0.016497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,75,CH,1939,2012,1067.4,NaN,0.007171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,76,CH,1939,2013,1060.9,NaN,-0.00609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,77,CH,1939,2014,1066.1,NaN,0.004901,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,78,CH,1939,2015,1053.2,NaN,-0.0121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,79,CH,1939,2016,1034.4,NaN,-0.01785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,80,CH,1939,2017,1034.5,NaN,0.000097,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,81,CH,1939,2018,1036.8,NaN,0.002223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,82,CH,1939,2019,1046.3,NaN,0.009163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,83,CH,1939,2020,1045.6,NaN,-0.000669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,84,CH,1939,2021,1057.7,NaN,0.011572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,85,CH,1939,2022,1128.6,NaN,0.067032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,89,2022-10-28 00:00:00,Karl Laternser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
dfbki.drop(dfbki.index[25:29], inplace=True)
dfbki.tail(5)

,index,Zürcher Index der Wohnbaukosten,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
20,81,CH,1939,2018,1036.8,NaN,0.002223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,82,CH,1939,2019,1046.3,NaN,0.009163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,83,CH,1939,2020,1045.6,NaN,-0.000669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,84,CH,1939,2021,1057.7,NaN,0.011572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,85,CH,1939,2022,1128.6,NaN,0.067032,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
dfbki_neu = dfbki.drop(columns=["index", "Zürcher Index der Wohnbaukosten", "Unnamed: 1"])
dfbki_neu.shape

(25, 11)

In [67]:
dfbki_neu = dfbki_neu.rename(columns={"Unnamed: 2" : "Jahr", "Unnamed: 3" : "Stand"})

In [72]:
dfbki_neu2 = dfbki_neu[["Jahr", "Stand"]]
dfbki_neu2

    Jahr   Stand
0    NaN     NaN
1   Jahr  Stand¹
2   2000   887.1
3   2001   929.3
4   2002   928.4
5   2003   899.2
6   2004   907.6
7   2005   929.5
8   2006   944.5
9   2007   987.4
10  2008  1026.8
11  2009  1030.7
12  2010  1042.6
13  2011  1059.8
14  2012  1067.4
15  2013  1060.9
16  2014  1066.1
17  2015  1053.2
18  2016  1034.4
19  2017  1034.5
20  2018  1036.8
21  2019  1046.3
22  2020  1045.6
23  2021  1057.7
24  2022  1128.6

In [73]:
dfbki_neu2.drop(dfbki_neu2.index[[0,1]], inplace=True)
dfbki_neu2

/var/folders/t8/xl0xzpb57bz854gpvcy7rr_r0000gn/T/ipykernel_68793/3387144758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfbki_neu2.drop(dfbki_neu2.index[[0,1]], inplace=True)

    Jahr   Stand
2   2000   887.1
3   2001   929.3
4   2002   928.4
5   2003   899.2
6   2004   907.6
7   2005   929.5
8   2006   944.5
9   2007   987.4
10  2008  1026.8
11  2009  1030.7
12  2010  1042.6
13  2011  1059.8
14  2012  1067.4
15  2013  1060.9
16  2014  1066.1
17  2015  1053.2
18  2016  1034.4
19  2017  1034.5
20  2018  1036.8
21  2019  1046.3
22  2020  1045.6
23  2021  1057.7
24  2022  1128.6

In [74]:
dfbki_neu2 = dfbki_neu2.reset_index()
dfbki_neu2

    index  Jahr   Stand
0       2  2000   887.1
1       3  2001   929.3
2       4  2002   928.4
3       5  2003   899.2
4       6  2004   907.6
5       7  2005   929.5
6       8  2006   944.5
7       9  2007   987.4
8      10  2008  1026.8
9      11  2009  1030.7
10     12  2010  1042.6
11     13  2011  1059.8
12     14  2012  1067.4
13     15  2013  1060.9
14     16  2014  1066.1
15     17  2015  1053.2
16     18  2016  1034.4
17     19  2017  1034.5
18     20  2018  1036.8
19     21  2019  1046.3
20     22  2020  1045.6
21     23  2021  1057.7
22     24  2022  1128.6

In [76]:
dfbki_neu2 = dfbki_neu2.drop(columns=["index"])
dfbki_neu2

    Jahr   Stand
0   2000   887.1
1   2001   929.3
2   2002   928.4
3   2003   899.2
4   2004   907.6
5   2005   929.5
6   2006   944.5
7   2007   987.4
8   2008  1026.8
9   2009  1030.7
10  2010  1042.6
11  2011  1059.8
12  2012  1067.4
13  2013  1060.9
14  2014  1066.1
15  2015  1053.2
16  2016  1034.4
17  2017  1034.5
18  2018  1036.8
19  2019  1046.3
20  2020  1045.6
21  2021  1057.7
22  2022  1128.6

In [78]:
dfbki_neu2.dtypes

Jahr     object
Stand    object
dtype: object

In [80]:
dfbki_neu2["Stand"] = dfbki_neu2["Stand"].astype(float)
dfbki_neu2.dtypes

Jahr      object
Stand    float64
dtype: object